name: Deploy JavaDoc mit mvn site

on:
  workflow_dispatch

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Create javadoc pages
      run: mvn -B package --file pom.xml site
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        name: Deploy JAvaDoc
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .docs
