name: Artifacts mit Maven

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Create a jar
      run: mvn -B package --file pom.xml package
    - name: Archive the jar as an artifact
    - uses: actions/upload-artifact@v2
      with:
        name: jar file
        path: target/*.jar
      
