name: JavaDoc mit mvn site im Branch documentationAction

on:
  push:
    branches: 
      documentationAction

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Dokumentieren with mvn site
      run: mvn -B package --file pom.xml site
